[build]
  base = "frontend-app"
  publish = "dist"
  command = "npm run build"

[[redirects]]
from = "/api/*"
to = "https://ai-ui-generator-backend-zc7e.onrender.com/api/:splat"
status = 200
force = true